### ISSUE TITLE
Spellchecker highlights hexadecimal CSS colors within a string

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-spellchecker#2]
Example string:
```
        "table.sql tr:nth-child(2n+1).highlight td.highlight\n" +
        "{\n" +
        "  background-color: #F0AAAA;\n" +
        "}\n"
```

Spellchecker highlighths AAAA part as invalid.

**Comment by VISTALL** [comment]
Hello. You can use code block as inside triple ` (```)

```java
"table.sql tr:nth-child(2n+1).highlight td.highlight\n" +
"{\n" +
" background-color: #F0AAAA;\n" +
"}\n"
```

There a problem with code. 

It's java string. Simple string - and spellchecker don't known what is it.

But - when you try to inject CSS language into string there same warn (and syntax problem)

![image](https://user-images.githubusercontent.com/542934/136674500-c68cd6c6-e5b4-40ae-aa6d-8e57032d8620.png)

Without CSS injection - spellckeck warning legal and correct.

In theory - need inject CSS, and fix problem with spellchecker with injection.

**Comment by unv-unv** [comment]
There's no syntax problem. CSS is syntactically correct, you just need to support :nth-child(...) selector.

And after CSS injection Spellchecker still highlights part of hexadecimal number as a typo:
![изображение](https://user-images.githubusercontent.com/16825982/136687037-218070df-9f13-4592-b014-78100cf334c4.png)
